### ISSUE TITLE
Missing header files

### ISSUE THREAD

**Issue by czcbangkai** [krajj7/spectrogram#1]
Hi! I am now working on a project about sound and spectrogram. Your amazing tool is really helpful for our further progress. But when I go through your code, I find several header files missing, such as <sndfile.hh> and "mad.h", also for the class SndfileHandle, I do not see its definition. So can you slightly clarify how to solve these issues? Actually, I just want to input an audio file and get a spectrogram by running the program on command line instead of Qt interfaces. I will be extremely appreciable if you could assist me on that issue, as well. Thanks a lot!

**Comment by krajj7** [comment]
Hi Jim,

The header and the class you mention come with libraries that my project depends on. They are listed in the docs: http://krajj7.github.io/spectrogram/prog.html (only the Qt4 link is bad). If you're developing on Linux, you might be able to just get the libraries from your package manager (commands for Debian are listed on the doc page). For Windows you'd probably have to build all of them from scratch, so I recommend starting with Linux.

The program currently doesn't have a command line interface, but you might be able to implement it. The logic is decoupled from the GUI.

**Comment by czcbangkai** [comment]
Hi Jan,

Thank so much for your information! I've tried to install those dependency packages, and started to work on the command line implementation. I hope that everything could go smoothly.

Thanks again.
